# Generated by Django 2.2.1 on 2020-05-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200519_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='promociones',
            name='icono',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
