# Generated by Django 2.2.1 on 2020-05-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_promociones_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio_fam', models.IntegerField()),
                ('precio_ind', models.IntegerField()),
                ('ingredientes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('FA', 'Familiar'), ('IN', 'Individual')], max_length=2),
        ),
    ]
