# Generated by Django 2.2.1 on 2020-05-20 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200519_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu',
        ),
    ]
